### ISSUE TITLE
请问，这个EFI适用于哪些系统？

### ISSUE THREAD

**Issue by kidxiang** [iDevon/Lenovo-K29-BigSur-OpenCore0.7.8-EFI#1]
请问，这个EFI适用于哪些系统？

**Comment by iDevon** [comment]
这个EFI只适用于Lenovo zhaoyang K29 安装Bigsur，
如安装Monterey需要更新驱动。
并且这个机型安装Monterey并没有测试过，不知道会不会特别卡。。。
> 请问，这个EFI适用于哪些系统？

**Comment by kidxiang** [comment]
感谢答复！我也是正在用联系召阳K29。再请教一下，Catalina可以用吗？

**Comment by iDevon** [comment]
> 感谢答复！我也是正在用联系召阳K29。再请教一下，Catalina可以用吗？

Catalina 也可以，但是机型需要改成10.2 ，其他硬件是否一样。

**Comment by kidxiang** [comment]
我的CPU是i7-3632QM，用ssdtPRGen.sh生成了ssdt.aml，替换了你文件里原本的，并且了删除了CPUFriendDataProvider.kext和CPUFriend.kext两个驱动，在OCC里也禁用了这两个驱动。并且按你所说的，在OCC里将机型平台改为了MacBookPro10,2和对应的我原本的序列号等内容。
我就做了以上修改。

我原本用的Clover，就想用修改后的EFI文件夹替换我Clover的EFI文件夹（当然是先完全删除，再复制过来），但这样做了后，在重启时，出现以下启动界面

![image](https://user-images.githubusercontent.com/54562626/158113672-c23582d1-7872-4ca8-a399-c713b1626628.jpeg)

我选择了reset NVRAM，系统自动重启了，但还是出现图片的这个画面，不敢再点击。

我又替换回了原本的Clover，系统还好启动起来了。
请问，我替换为你的EFI的操作正确吗？怎么才能通过opencore引导系统呢？

**Comment by iDevon** [comment]
如果系统是Big Sur机型就应该选择11.2  。你应该是efi里面的设置问题，

发自我的iPhone

**Comment by kidxiang** [comment]
折腾了几天，还是搞不好，我还是老老实实用clover吧

**Comment by iDevon** [comment]
>折腾了几天，还是搞不好，我还是老实实用clover吧

不知道是不是需要重新使用OC引导安装才可行。
你可以将OC EFI放在U盘里面用U盘引导试试。
方便的话加我：58518810

**Comment by iDevon** [comment]
加我58518810

发自我的iPhone
